image: golang
stages:
    - test
    - build

before_script:
    - sed -i "173.194.75.141 golang.org golang " /etc/hosts
    - sed -i "203.208.46.1 golang.org golang " /etc/hosts

test:
    stage: test
    script:
        - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
        - chmod +x gpm
        - ./gpm install
        - ./test.sh
build:
    stage: build
    script:
        - go build

