image: golang
stages:
    - test
    - build

before_script:
    - mkdir -p ~/src/github.com/bitly/oauth2_proxy
    - cp -r . ~/src/github.com/bitly/oauth2_proxy
    - cd ~/src/github.com/bitly/oauth2_proxy
test:
    stage: test
    variables:
        GOPATH: /root
    script:
        - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
        - chmod +x gpm
        - ./gpm install
        - ./test.sh
    tags:
        - hongkong
build:
    stage: build
    variables:
        GOPATH: /root
    script:
        - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
        - chmod +x gpm
        - ./gpm install
        - env GOOS=linux GOARCH=386 go build -o build/oauth2_proxy
        - ls build
    artifacts:
      expire_in: 60 mins
      untracked: true
      name: "oauth2-proxy-linux-x86"
      paths:
        - build/
    tags:
        - hongkong

