image: golang
stages:
    - test
    - build

before_script:
    - mkdir ~/src/github.com/bitly/oauth2_proxy
    - cp -r . ~/src/github.com/bitly/oauth2_proxy
    - cd ~/src/github.com/bitly/oauth2_proxy
test:
    stage: test
    variables:
        GOPATH: ~/
    script:
        - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
        - chmod +x gpm
        - ./gpm install
        - ./test.sh
    tags:
        - hongkong
build:
    stage: build
    variables:
        GOPATH: ~/
    script:
        - go build
    tags:
        - hongkong

